name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run: |
        surge --project ./ --examdevops.surge.sh
      env:
        SURGE_LOGIN: ${{ christopher300804@gmail.com }}
        SURGE_TOKEN: ${{ 15ba8ee4e3bc4d194176949770a52887 }}
